## menggunakan nodeport service agar bisa mengakses pod dari luar

## flow nya -> kubernetes akan membuat IP & port untuk setiap nodes
##          -> akses IP&port node nya dari luar / browser
##
##  Untuk mengakses nya gunakan command `minikube service <nama service>

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-alpine
  template:
    metadata:
      name: nginx-rs
      labels:
        name: nginx-alpine
    spec:
      containers:
        - name: nginx-alpine
          image: nginx:stable-alpine
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: expose-service
spec:
  type: NodePort
  selector:
    name: nginx-alpine # Sesuai dengan label pada pods / replicaset yang akan di jalankan 
  ports:
    - port: 80
      targetPort: 80 
      nodePort: 32613 ## port untuk nodes nya

