apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    environment: acc
spec:
  replicas: 3
  # value Selector harus sama dengan labels yang ada pada template
  # karena selama replika tidak terpenuhi, selector akan terus memanggil template labels
  selector:
    app: nginx-alpine
  template:
    metadata:
      name: nginx-alpine #nama pod
      labels:
        app: nginx-alpine # untuk selector
    spec:
      containers:
        - name: nginx-alpine-rc
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1