apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx-alpine
  template:
    metadata:
      name: nginx-rs
      labels:
        name: nginx-alpine
    spec:
      containers:
        - name: nginx-alpine
          image: nginx:stable-alpine
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    name: nginx-alpine # Sesuai dengan label pada pods / replicaset yang akan di jalankan 
  ports:
    - port: 8080
      targetPort: 80

---
## hanya untuk test
## masuk ke dalam pod curl dengan command
##      kubectl exec -it <nama pod (curl)> -- /bin/sh
## di dalam shell ketikkan `curl http://{CLUSTER_IP}:PORT  
## cara lainnya yaitu dengan DNS & environment variable
##
## Menggunakan DNS -> http://<servicename>.<namespace>.svc.cluster.local:<port>
## Menggunakan envVar -> http://{$NGINX_SERVICE_SERVICE_HOST}:{$NGINX_SERVICE_SERVICE_PORT}
apiVersion: v1
kind: Pod
metadata:
  name: curl
  labels:
    name: curl
spec:
  containers:
    - name: curl
      image: pimenvibritania/nginx-curl